static const char tune[] = "ACGgbGA ACEGgFD ACGgbEC FGAGFED "
			   "CEGAEC GBgfeD ACGEFGA DEFGEDC "
			   "ACGgbGA ACEGgFD ACGgbEC FGAGFED "
			   "EGCEGA DFABAG CEGBAF DFACBG "
			   "GABCDEF EGABCDE BAGFEDC ACEGFED "
			   "CEGAGEC GBgfeD ACGEFGA DEFGEDC";
