// Auto-generated by Editor
#ifndef LEVEL_DATA_H
#define LEVEL_DATA_H

#include "common.h"

player P_Init = { 263, -12, 30, 40, 0 };

struct Map current_map = {
    .name = "Generated Map",
    .filename = "level_data.h",
    .num_sectors = 6,
    .sectors = {
        { // Sector 0
            .floor = {
                .walkable = 1,
                .texture_tile_x = 0, .texture_tile_y = 0,
                .texture = { .texture_index = 8, .shade = 0 }
            },
            .walls = {
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 8, .shade = 0 },
                    .bottom_height = 95,
                    .top_height = 100,
                    .p1_x = 64, .p1_y = 32,
                    .p2_x = 512, .p2_y = 32
                },
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 8, .shade = 90 },
                    .bottom_height = 95,
                    .top_height = 100,
                    .p1_x = 512, .p1_y = 32,
                    .p2_x = 512, .p2_y = 448
                },
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 8, .shade = 0 },
                    .bottom_height = 95,
                    .top_height = 100,
                    .p1_x = 512, .p1_y = 448,
                    .p2_x = 64, .p2_y = 448
                },
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 8, .shade = 90 },
                    .bottom_height = 95,
                    .top_height = 100,
                    .p1_x = 64, .p1_y = 448,
                    .p2_x = 64, .p2_y = 32
                },
            },
            .distance = 0,
            .surface = 0
        },
        { // Sector 1
            .floor = {
                .walkable = 1,
                .texture_tile_x = 0, .texture_tile_y = 0,
                .texture = { .texture_index = 8, .shade = 0 }
            },
            .walls = {
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 8, .shade = 0 },
                    .bottom_height = 0,
                    .top_height = 25,
                    .p1_x = 128, .p1_y = 288,
                    .p2_x = 256, .p2_y = 288
                },
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 8, .shade = 90 },
                    .bottom_height = 0,
                    .top_height = 25,
                    .p1_x = 256, .p1_y = 288,
                    .p2_x = 256, .p2_y = 416
                },
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 8, .shade = 0 },
                    .bottom_height = 0,
                    .top_height = 25,
                    .p1_x = 256, .p1_y = 416,
                    .p2_x = 128, .p2_y = 416
                },
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 8, .shade = 90 },
                    .bottom_height = 0,
                    .top_height = 25,
                    .p1_x = 128, .p1_y = 416,
                    .p2_x = 128, .p2_y = 288
                },
            },
            .distance = 0,
            .surface = 0
        },
        { // Sector 2
            .floor = {
                .walkable = 1,
                .texture_tile_x = 0, .texture_tile_y = 0,
                .texture = { .texture_index = 8, .shade = 0 }
            },
            .walls = {
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 11, .shade = 0 },
                    .bottom_height = 0,
                    .top_height = 40,
                    .p1_x = 128, .p1_y = 224,
                    .p2_x = 192, .p2_y = 224
                },
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 11, .shade = 90 },
                    .bottom_height = 0,
                    .top_height = 40,
                    .p1_x = 192, .p1_y = 224,
                    .p2_x = 192, .p2_y = 288
                },
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 11, .shade = 0 },
                    .bottom_height = 0,
                    .top_height = 40,
                    .p1_x = 192, .p1_y = 288,
                    .p2_x = 128, .p2_y = 288
                },
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 11, .shade = 90 },
                    .bottom_height = 0,
                    .top_height = 40,
                    .p1_x = 128, .p1_y = 288,
                    .p2_x = 128, .p2_y = 224
                },
            },
            .distance = 0,
            .surface = 0
        },
        { // Sector 3
            .floor = {
                .walkable = 1,
                .texture_tile_x = 0, .texture_tile_y = 0,
                .texture = { .texture_index = 8, .shade = 0 }
            },
            .walls = {
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 11, .shade = 0 },
                    .bottom_height = 65,
                    .top_height = 95,
                    .p1_x = 128, .p1_y = 96,
                    .p2_x = 192, .p2_y = 96
                },
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 11, .shade = 90 },
                    .bottom_height = 65,
                    .top_height = 95,
                    .p1_x = 192, .p1_y = 96,
                    .p2_x = 192, .p2_y = 160
                },
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 11, .shade = 0 },
                    .bottom_height = 65,
                    .top_height = 95,
                    .p1_x = 192, .p1_y = 160,
                    .p2_x = 128, .p2_y = 160
                },
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 11, .shade = 90 },
                    .bottom_height = 65,
                    .top_height = 95,
                    .p1_x = 128, .p1_y = 160,
                    .p2_x = 128, .p2_y = 96
                },
            },
            .distance = 0,
            .surface = 0
        },
        { // Sector 4
            .floor = {
                .walkable = 1,
                .texture_tile_x = 0, .texture_tile_y = 0,
                .texture = { .texture_index = 7, .shade = 0 }
            },
            .walls = {
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 11, .shade = 0 },
                    .bottom_height = 80,
                    .top_height = 95,
                    .p1_x = 128, .p1_y = 160,
                    .p2_x = 192, .p2_y = 160
                },
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 11, .shade = 90 },
                    .bottom_height = 80,
                    .top_height = 95,
                    .p1_x = 192, .p1_y = 160,
                    .p2_x = 192, .p2_y = 224
                },
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 11, .shade = 0 },
                    .bottom_height = 80,
                    .top_height = 95,
                    .p1_x = 192, .p1_y = 224,
                    .p2_x = 128, .p2_y = 224
                },
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 11, .shade = 90 },
                    .bottom_height = 80,
                    .top_height = 95,
                    .p1_x = 128, .p1_y = 224,
                    .p2_x = 128, .p2_y = 160
                },
            },
            .distance = 0,
            .surface = 0
        },
        { // Sector 5
            .floor = {
                .walkable = 1,
                .texture_tile_x = 0, .texture_tile_y = 0,
                .texture = { .texture_index = 8, .shade = 0 }
            },
            .walls = {
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 11, .shade = 0 },
                    .bottom_height = 0,
                    .top_height = 40,
                    .p1_x = 128, .p1_y = 160,
                    .p2_x = 192, .p2_y = 160
                },
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 11, .shade = 90 },
                    .bottom_height = 0,
                    .top_height = 40,
                    .p1_x = 192, .p1_y = 160,
                    .p2_x = 192, .p2_y = 224
                },
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 11, .shade = 0 },
                    .bottom_height = 0,
                    .top_height = 40,
                    .p1_x = 192, .p1_y = 224,
                    .p2_x = 128, .p2_y = 224
                },
                {
                    .active = 1,
                    .solid = 1,
                    .texture_scale = 1,
                    .texture = { .texture_index = 11, .shade = 90 },
                    .bottom_height = 0,
                    .top_height = 40,
                    .p1_x = 128, .p1_y = 224,
                    .p2_x = 128, .p2_y = 160
                },
            },
            .distance = 0,
            .surface = 0
        },
    }
};

#endif
