#!/bin/bash -e

if ! test -e build/combined; then
  cmake -B build/combined src -G Ninja -DENABLE_OFFSETS=ON
fi

cmake --build build/combined

firmwares=$(
  grep ENABLE_OFFSETS src/*/CMakeLists.txt \
    | cut -d: -f1 | sed -e 's#/CMakeLists.txt##' -e 's#src/##' -e 's#.*#build/combined/\0/\0.uf2#'
)

cat ${firmwares} >build/combined.uf2

echo -e "\e[1;32mCompiled build/combined.uf2\e[0m"

# EOF
