#!/bin/bash -e

if ! test -e build/combined; then
  cmake -B build/combined src -G Ninja -DENABLE_OFFSETS=ON
fi

cmake --build build/combined

firmwares=$(
  ls -1 src/*/memmap.ld | sed -e 's#/memmap.ld##' -e 's#src/##' -e 's#.*#build/combined/\0/\0.uf2#'
)

cat ${firmwares} >build/combined.uf2

echo -e "\e[1;32mCompiled build/combined.uf2\e[0m"

# EOF
