#pragma once

// Screen and tile dimensions
#define TILE_SIZE 8
#define MAP_ROWS 15
#define MAP_COLS 48

typedef enum {
	EMPTY = 0,
	FLOOR_MID = 1,
	FLOOR_L = 2,
	FLOOR_R,
	FLOOR_JUMP_MID,
	FLOOR_JUMP_L,
	FLOOR_JUMP_R,
	FLOOR_WIN_MID,
	FLOOR_WIN_L,
	FLOOR_WIN_R,
	SPAWNER_MARIO,
	SPAWNER_SONIC,
	GRASS,
	CHEST,
	FLOOR_MID_COLD,
	FLOOR_L_COLD,
	FLOOR_R_COLD,
	FLOOR_CUBE_COLD,
	FLOOR_JUMP_MID_COLD,
	FLOOR_JUMP_L_COLD,
	FLOOR_JUMP_R_COLD,
	FLOOR_JUMP_CUBE_COLD,
	FLOOR_WIN_MID_COLD,
	FLOOR_WIN_L_COLD,
	FLOOR_WIN_R_COLD,
	FLOOR_WIN_CUBE_COLD
} TileType;
